# This workflow will install meson (via python), build the project and run tests

name: Build & Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install meson ninja
    - uses: ilammy/msvc-dev-cmd@v1 
    - name: Meta-Build (meson)
      if: ${{ matrix.platform != 'windows-latest' }}
      run: |
        meson bin
    - name: Meta-Build (meson)
      if: ${{ matrix.platform == 'windows-latest' }}
      env:
        CC: cl
      run: |
        meson bin
    - name: Build (ninja)
      run: ninja -C bin
    - name: Run tests
      run: ninja -C bin test
